---
title: Highcharter Drilldown on Neuropsychological Domains and Test Scores
subtitle: ""
summary: ""
patient: "Biggie"
author: runner
authors: [admin]
date: '2022-04-05'
slug: highcharter-drilldown-neurocognitive-domains
categories:
  - R
  - highcharter
tags:
  - ggplot2
  - R
  - R Markdown
lastmod: '2022-04-05T13:50:26-07:00'
featured: no
draft: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
output:
  blogdown::html_page:
    toc: false
    fig_width: 12
    fig_height: 8
    fig_retina: 3
    dev: "svg"
rmd_hash: ad12fe1c1b68566d
---

```{r patient, include=FALSE}
patient <- "Biggie"
```

```{r setup, include=FALSE}
## load libraries
library(here)
library(knitr)
library(xaringan)
library(xaringanExtra)
library(xaringanthemer)
library(rmarkdown)
library(revealjs)
library(reactable)
library(tidyverse)
library(highcharter)
library(htmlwidgets)
library(widgetframe)
library(crosstalk)
library(manipulateWidget)
library(tibble)
library(svglite)
library(gifski)
library(bwu)
## knitr options
options(htmltools.dir.version = FALSE)
knitr::opts_chunk$set(
  fig.path = "figs/",
  fig.width = 12,
  fig.height = 8,
  fig.asp = .5,
  fig.retina = 3,
  out.width = "100%",
  fig.showtext = TRUE,
  comment = NULL,
  cache = FALSE,
  cache.path = "cache/",
  echo = FALSE,
  message = FALSE,
  warning = FALSE,
  dev = c("svg", "svglite"),
  hiline = TRUE
)
knitr::opts_chunk$set(collapse = TRUE, class.source = c("aside", "img", ".drilld", "rect"))
```

## Neuropsychological Testing Results

```{r, read-data}
neurocog <-
  readr::read_csv(here::here("static", "data", "neurocog.csv"), show_col_types = FALSE)
```

```{css, echo=FALSE}
aside {
  margin-left: 100%;
  position: absolute;
}
```

```{css, echo=FALSE}
img {
  width: 200vw;
  margin-left: calc(50% - 50vw);
}
```

```{css, echo=FALSE}
rect[Attributes Style] {
    fill: transparent;
    x: 0;
    y: 0;
    width: 1200;
    height: 800;
    rx: 0;
    ry: 0;
}
```

```{css, echo=FALSE}
.drilld {
  width: 300vw;
  margin-left: calc(50% - 50vw);
}
```

```{r drilldown-level1}
## Level 1
## Domain scores
# 1. create mean z-scores for domain
ncog1 <- neurocog %>%
  dplyr::group_by(domain) %>%
  dplyr::summarize(zMean = mean(z),
                   zPct = mean(percentile)) %>%
  dplyr::mutate(range = NA)
ncog1$zMean <- round(ncog1$zMean, 2L)
ncog1$zPct <- round(ncog1$zPct, 0L)
ncog1 <-
  ncog1 %>%
  dplyr::mutate(
    range = dplyr::case_when(
      zPct >= 98 ~ "Exceptionally High",
      zPct %in% 91:97 ~ "Above Average",
      zPct %in% 75:90 ~ "High-Average",
      zPct %in% 25:74 ~ "Average",
      zPct %in% 9:24 ~ "Low-Average",
      zPct %in% 2:8 ~ "Below Average",
      zPct < 2 ~ "Exceptionally Low",
      TRUE ~ as.character(range)
    )
  )

# 2. sort hi to lo
ncog1 <- arrange(ncog1, desc(zMean))

# 3. create tibble with new column with domain name lowercase
ncog_level1_status <- tibble(
  name = ncog1$domain,
  y = ncog1$zMean,
  y2 = ncog1$zPct,
  range = ncog1$range,
  drilldown = tolower(name)
)
```

```{r drilldown-level2}
## Level 2
## Subdomain scores
## function to create second level of drilldown (subdomain scores)
ncog_level2_drill <-
  lapply(unique(neurocog$domain), function(x_level) {
    ncog2 <- subset(neurocog, neurocog$domain %in% x_level)
    
    # same as above
    ncog2 <-
      ncog2 %>%
      group_by(subdomain) %>%
      summarize(zMean = mean(z),
                zPct = mean(percentile)) %>%
      mutate(range = NA)
    
    # round z-score to 1 decimal
    ncog2$zMean <- round(ncog2$zMean, 2L)
    ncog2$zPct <- round(ncog2$zPct, 0L)
    ncog2 <-
      ncog2 %>%
      dplyr::mutate(
        range = dplyr::case_when(
          zPct >= 98 ~ "Exceptionally High",
          zPct %in% 91:97 ~ "Above Average",
          zPct %in% 75:90 ~ "High-Average",
          zPct %in% 25:74 ~ "Average",
          zPct %in% 9:24 ~ "Low-Average",
          zPct %in% 2:8 ~ "Below Average",
          zPct < 2 ~ "Exceptionally Low",
          TRUE ~ as.character(range)
        )
      )
    
    # 2. sort hi to lo
    ncog2 <- arrange(ncog2, desc(zMean))
    
    # 3. create tibble with new column with domain name lowercase
    ncog_level2_status <- tibble(
      name = ncog2$subdomain,
      y = ncog2$zMean,
      y2 = ncog2$zPct,
      range = ncog2$range,
      drilldown = tolower(paste(x_level, name, sep = "_"))
    )
    
    list(
      id = tolower(x_level),
      type = "column",
      data = list_parse(ncog_level2_status)
    )
  })
```

```{r drilldown-level3}
## Level 3
## Narrow subdomains
## reuse function
ncog_level3_drill <-
  lapply(unique(neurocog$domain), function(x_level) {
    ncog2 <- subset(neurocog, neurocog$domain %in% x_level)
    
    # reuse function but with y_level
    lapply(unique(ncog2$subdomain), function(y_level) {
      # 1. create mean z-scores for subdomain
      # ncog3 becomes pronoun for domain
      ncog3 <- subset(ncog2, ncog2$subdomain %in% y_level)
      
      ncog3 <- ncog3 %>%
        group_by(narrow) %>%
        summarize(zMean = mean(z), zPct = mean(percentile)) %>%
        mutate(range = NA)
      
      # round z-score to 1 decimal
      ncog3$zMean <- round(ncog3$zMean, 2L)
      ncog3$zPct <- round(ncog3$zPct, 0L)
      ncog3 <-
        ncog3 %>%
        dplyr::mutate(
          range = dplyr::case_when(
            zPct >= 98 ~ "Exceptionally High",
            zPct %in% 91:97 ~ "Above Average",
            zPct %in% 75:90 ~ "High-Average",
            zPct %in% 25:74 ~ "Average",
            zPct %in% 9:24 ~ "Low-Average",
            zPct %in% 2:8 ~ "Below Average",
            zPct < 2 ~ "Exceptionally Low",
            TRUE ~ as.character(range)
          )
        )
      
      ncog3 <- arrange(ncog3, desc(zMean))
      
      ncog_level3_status <- tibble(
        name = ncog3$narrow,
        y = ncog3$zMean,
        y2 = ncog3$zPct,
        range = ncog3$range,
        drilldown = tolower(paste(x_level, y_level, name, sep = "_"))
      )
      
      list(
        id = tolower(paste(x_level, y_level, sep = "_")),
        type = "column",
        data = list_parse(ncog_level3_status)
      )
    })
  }) %>% unlist(recursive = FALSE)
```

```{r drilldown-level4}
## Level 4
## Scale scores
## reuse both functions
ncog_level4_drill <-
  lapply(unique(neurocog$domain), function(x_level) {
    ncog2 <- subset(neurocog, neurocog$domain %in% x_level)
    
    lapply(unique(ncog2$subdomain), function(y_level) {
      ncog3 <- subset(ncog2, ncog2$subdomain %in% y_level)
      
      lapply(unique(ncog3$narrow), function(z_level) {
        ncog4 <- subset(ncog3, ncog3$narrow %in% z_level)
        
        ncog4 <-
          ncog4 %>%
          group_by(scale) %>%
          summarize(zMean = mean(z),
                    zPct = mean(percentile)) %>%
          mutate(range = NA)
        
        # round z-score to 1 decimal
        ncog4$zMean <- round(ncog4$zMean, 2L)
        ncog4$zPct <- round(ncog4$zPct, 0L)
        ncog4 <-
          ncog4 %>%
          dplyr::mutate(
            range = dplyr::case_when(
              zPct >= 98 ~ "Exceptionally High",
              zPct %in% 91:97 ~ "Above Average",
              zPct %in% 75:90 ~ "High-Average",
              zPct %in% 25:74 ~ "Average",
              zPct %in% 9:24 ~ "Low-Average",
              zPct %in% 2:8 ~ "Below Average",
              zPct < 2 ~ "Exceptionally Low",
              TRUE ~ as.character(range)
            )
          )
        
        ncog4 <- arrange(ncog4, desc(zMean))
        
        ncog_level4_status <- tibble(
          name = ncog4$scale,
          y = ncog4$zMean,
          y2 = ncog4$zPct,
          range = ncog4$range
        )
        
        list(
          id = tolower(paste(x_level, y_level, z_level, sep = "_")),
          type = "column",
          data = list_parse(ncog_level4_status)
        )
      })
    }) %>% unlist(recursive = FALSE)
  }) %>% unlist(recursive = FALSE)
```

```{r}
thm_merge <- hc_theme_merge(
  hc_theme_monokai(),
  hc_theme_darkunica()
)
```

```{r drilldown-plot, fig.cap='HighchartR Drilldown', fig.width=12, fig.height=8, fig.retina=3, out.width = "100%"}
# Tooltip
x <- c("Name", "Score", "Percentile", "Range")
y <- c("{point.name}", "{point.y}", "{point.y2}", "{point.range}")
tt <- tooltip_table(x, y)

## Create drilldown bar plot zscores
plot1 <-
  highchart() %>%
    hc_title(
      text = patient,
      style = list(
        fontSize = "15px")) %>%
    hc_add_series(
      ncog_level1_status,
      type = "bar",
      name = "Neuropsychological Test Scores",
      hcaes(x = name, y = y)) %>%
    hc_xAxis(
      type = "category",
      title = list(
        text = "Domain"),
      categories = .$name) %>%
    hc_yAxis(
      title = list(
        text = "Z-Score (M = 0, SD = 1)"),
      labels = list(
        format = "{value}")) %>%
    hc_tooltip(
      pointFormat = tt,
      useHTML = TRUE,
      valueDecimals = 1) %>%
    hc_plotOptions(
      series = list(
        colorByPoint = TRUE,
        allowPointSelect = TRUE,
        dataLabels = TRUE)) %>%
    hc_drilldown(
      allowPointDrilldown = TRUE,
      series = c(
        ncog_level2_drill,
        ncog_level3_drill,
        ncog_level4_drill)) %>%
    hc_colorAxis(
      minColor = "red",
      maxColor = "blue") %>%
    hc_add_theme(
      thm_merge) %>% 
    hc_chart(
      style = list(
        fontFamily = "Cabin"),
      backgroundColor = list("gray")
    )
frameWidget(plot1)
```
