---
title: More ghetto code
author: Joey Trampush
date: '2021-06-18'
slug: more-ghetto-code
categories:
  - R
  - rmarkdown
tags:
  - R Markdown
subtitle: 'bad code'
summary: 'drilldown plot in highcharter'
authors: [joey]
lastmod: '2021-06-18T18:11:39-07:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: [data-visualization]
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(collapse = TRUE)
```

# Highcharter Drilldown

```{r, tidy=FALSE, echo=F}
## Highcharter Drilldown
library(blogdown)
library(rmarkdown)
library(revealjs)
library(xaringan)
library(xaringanExtra)
library(xaringanthemer)
library(dataui)
library(reactable)
## Import CSV files
library(dplyr)
library(readr)
library(forcats)
library(purrr)
library(highcharter)
library(tidyverse)
library(widgetframe)
```

```{r echo=F}
# patient
patient <- "patient"
# path to files
data_path <-
  here::here("~/blogdown.brainworkup/content/post/2021-06-18-more-ghetto-code/csv")
# get file names of .csv files
files <- dir(data_path, pattern = "*.csv")
# read into env

neuropsych <-
  files %>%
  purrr::set_names() %>%
  purrr::map_df( ~ readr::read_csv(file.path(data_path, .)),
                 na = c("", "NA", "--", "-"),
                 .id = "filename") %>%
  dplyr::filter(!is.na(percentile)) %>%
  dplyr::distinct() %>%
  dplyr::mutate(z = qnorm(percentile / 100))

neuropsych <- neuropsych %>%
  dplyr::mutate(domain = forcats::as_factor(domain)) %>%
  dplyr::mutate(subdomain = forcats::as_factor(subdomain)) %>%
  dplyr::mutate(narrow = forcats::as_factor(narrow)) %>%
  dplyr::mutate(domain_broad = forcats::as_factor(domain_broad)) %>%
  dplyr::mutate(domain_test = forcats::as_factor(domain_test)) %>%
  #dplyr::mutate(verbal = forcats::as_factor(verbal)) %>%
  dplyr::mutate(pass = forcats::as_factor(pass)) %>%
  dplyr::mutate(timed = forcats::as_factor(timed))
```

## Percentiles

```{r echo=F}
ncog <- neuropsych %>%
  group_by(domain) %>%
  summarize(Pct = mean(percentile)
  )

ncog <- arrange(ncog, desc(Pct))

## Level 1
ncogL1status <- tibble(
  name = ncog$domain,
   y = ncog$Pct,
    drilldown = tolower(name))

## Level 2
ncogL2drill <- lapply(unique(neuropsych$domain), function(x_level) {
  ncog2 <- subset(neuropsych, neuropsych$domain %in% x_level)
  # ncog2 <- neuropsych[neuropsych$domain == x_level,]
  ncog2 <- ncog2 %>%
    group_by(subdomain) %>%
    summarize(Pct = mean(percentile))
  ncog2 <- arrange(ncog2, desc(Pct)) ### CHECK
  ncogL2status <- tibble(name = ncog2$subdomain, y = ncog2$Pct, drilldown = tolower(paste(x_level, name, sep = "_")))
  list(id = tolower(x_level), type = "column", data = list_parse(ncogL2status))
})

## Level 3
ncogL3drill <- lapply(unique(neuropsych$domain), function(x_level) {
  ncog2 <- subset(neuropsych, neuropsych$domain %in% x_level)
  # ncog2 <- neuropsych[neuropsych$domain == x_level,]
  lapply(unique(ncog2$subdomain), function(y_level) {
    ncog3 <- subset(ncog2, ncog2$subdomain %in% y_level)
    # ncog3 <- ncog2[ncog2$subdomain == y_level,]
    ncog3 <- ncog3 %>%
      group_by(narrow) %>%
      summarize(Pct = mean(percentile))
    ncog3 <- arrange(ncog3, desc(Pct))
    ncogL3status <- tibble(name = ncog3$narrow, y = ncog3$Pct, drilldown = tolower(paste(x_level, y_level, name, sep = "_")))
    list(id = tolower(paste(x_level, y_level, sep = "_")), type = "column", data = list_parse(ncogL3status))
  })
}) %>% unlist(recursive = FALSE)

## Level 4
ncogL4drill <- lapply(unique(neuropsych$domain), function(x_level) {
  ncog2 <- subset(neuropsych, neuropsych$domain %in% x_level)
  # ncog2 <- neuropsych[neuropsych$domain == x_level,]
  lapply(unique(ncog2$subdomain), function(y_level) {
    ncog3 <- subset(ncog2, ncog2$subdomain %in% y_level)
    # ncog3 <- ncog2[ncog2$subdomain == y_level,]
    lapply(unique(ncog3$narrow), function(z_level) {
      ncog4 <- subset(ncog3, ncog3$narrow %in% z_level)
      # ncog4 <- ncog3[ncog3$narrow == z_level,]
      ncog4 <- ncog4 %>%
        group_by(scale) %>%
        summarize(Pct = mean(percentile))
      ncog4 <- arrange(ncog4, desc(Pct))
      ncogL4status <- tibble(name = ncog4$scale, y = ncog4$Pct)
      list(id = tolower(paste(x_level, y_level, z_level, sep = "_")), type = "column", data = list_parse2(ncogL4status))
    })
  }) %>% unlist(recursive = FALSE)
}) %>% unlist(recursive = FALSE)
```

```{r drill, fig.cap='Drilldown Neuropsych', echo=F}
colors <-
  c(
    "#058DC7",
    "#50B432",
    "#ED561B",
    "#DDDF00",
    "#24CBE5",
    "#64E572",
    "#FF9655",
    "#FFF263",
    "#6AF9C4"
  )

colors8 <-
  c(
    "#058DC7",
    "#50B432",
    "#DDDF00",
    "#24CBE5",
    "#64E572",
    "#FF9655",
    "#FFF263",
    "#6AF9C4"
  )

## for Tooltip

ncogL1status <- ncogL1status %>%
  dplyr::mutate(
    range = case_when(
      y >= 98 ~ "Exceptionally High",
      y %in% 91:97 ~ "Above Average",
      y %in% 75:90 ~ "High-Average",
      y %in% 25:74 ~ "Average",
      y %in% 9:24 ~ "Low-Average",
      y %in% 2:8 ~ "Below Average",
      y < 2 ~ "Exceptionally Low",
      TRUE ~ as.character(y)
    )
  )

x <- c("Name", "Score", "Range")
y <- c("{point.name}", "{point.y}", "{point.range}")
tt <- tooltip_table(x, y)

# Create drilldown bar plot

frameWidget(
  highchart() %>%
    hc_title(text = patient,
             style = list(fontSize = "15px")) %>%
    hc_add_series(
      ncogL1status,
      type = "bar",
      name = "Neuropsychological Test Scores",
      hcaes(x = name, y = y, color = colors8)
    ) %>%
    hc_xAxis(
      type = "category",
      title = list(text = "Domain"),
      categories = .$name
    ) %>%
    hc_yAxis(
      title = list(text = "Percentile"),
      labels = list(format = "{value} ‰")
    ) %>%
    hc_tooltip(
      pointFormat = tt,
      useHTML = TRUE,
      valueDecimals = 0
    ) %>%
    hc_plotOptions(
      series = list(
        colorByPoint = TRUE,
        allowPointSelect = TRUE,
        dataLabels = TRUE
      )
    ) %>%
    hc_drilldown(
      allowPointDrilldown = TRUE,
      series = c(ncogL2drill, ncogL3drill, ncogL4drill)
    )
)
```

## zScores

```{r echo=F}
library(highcharter)
library(tidyverse)

ncogz <- neuropsych %>%
  group_by(domain) %>%
  summarize(zMean = mean(z)
  )

ncogz <- arrange(ncogz, desc(zMean))

## Level 1
ncogL1statusz <- tibble(
  name = ncogz$domain,
   y = ncogz$zMean,
    drilldown = tolower(name))

## Level 2
ncogL2drillz <- lapply(unique(neuropsych$domain), function(x_level) {
  ncog2z <- subset(neuropsych, neuropsych$domain %in% x_level)
  # ncog2z <- neuropsych[neuropsych$domain == x_level,]
  ncog2z <- ncog2z %>%
    group_by(subdomain) %>%
    summarize(zMean = mean(z))
  ncog2z <- arrange(ncog2z, desc(zMean)) ### CHECK
  ncogL2zstatus <- tibble(name = ncog2z$subdomain, y = ncog2z$zMean, drilldown = tolower(paste(x_level, name, sep = "_")))
  list(id = tolower(x_level), type = "column", data = list_parse(ncogL2zstatus))
})

## Level 3
ncogL3drillz <- lapply(unique(neuropsych$domain), function(x_level) {
  ncog2z <- subset(neuropsych, neuropsych$domain %in% x_level)
  # ncog2 <- neuropsych[neuropsych$domain == x_level,]
  lapply(unique(ncog2z$subdomain), function(y_level) {
    ncog3z <- subset(ncog2z, ncog2z$subdomain %in% y_level)
    # ncog3 <- ncog2[ncog2$subdomain == y_level,]
    ncog3z <- ncog3z %>%
      group_by(narrow) %>%
      summarize(zMean = mean(z))
    ncog3z <- arrange(ncog3z, desc(zMean))
    ncogL3zstatus <- tibble(name = ncog3z$narrow, y = ncog3z$zMean, drilldown = tolower(paste(x_level, y_level, name, sep = "_")))
    list(id = tolower(paste(x_level, y_level, sep = "_")), type = "column", data = list_parse(ncogL3zstatus))
  })
}) %>% unlist(recursive = FALSE)

## Level 4
ncogL4drillz <- lapply(unique(neuropsych$domain), function(x_level) {
  ncog2z <- subset(neuropsych, neuropsych$domain %in% x_level)
  # ncog2 <- neuropsych[neuropsych$domain == x_level,]
  lapply(unique(ncog2z$subdomain), function(y_level) {
    ncog3z <- subset(ncog2z, ncog2z$subdomain %in% y_level)
    # ncog3 <- ncog2[ncog2$subdomain == y_level,]
    lapply(unique(ncog3z$narrow), function(z_level) {
      ncog4z <- subset(ncog3z, ncog3z$narrow %in% z_level)
      # ncog4 <- ncog3[ncog3$narrow == z_level,]
      ncog4z <- ncog4z %>%
        group_by(scale) %>%
        summarize(zMean = mean(z))
      ncog4z <- arrange(ncog4z, desc(zMean))
      ncogL4zstatus <- tibble(name = ncog4z$scale, y = ncog4z$zMean)
      list(id = tolower(paste(x_level, y_level, z_level, sep = "_")), type = "column", data = list_parse2(ncogL4zstatus))
    })
  }) %>% unlist(recursive = FALSE)
}) %>% unlist(recursive = FALSE)
```

```{r drillz, fig.cap='Drilldown Neuropsych', echo=F, out.width="100%", out.height="100%"}
colors <-
  c(
    "#058DC7",
    "#50B432",
    "#ED561B",
    "#DDDF00",
    "#24CBE5",
    "#64E572",
    "#FF9655",
    "#FFF263",
    "#6AF9C4"
  )

colors8 <-
  c(
    "#058DC7",
    "#50B432",
    "#DDDF00",
    "#24CBE5",
    "#64E572",
    "#FF9655",
    "#FFF263",
    "#6AF9C4"
  )

## for Tooltip

ncogL1statusz <- ncogL1statusz %>%
  dplyr::mutate(
    range = case_when(
      y >= 98 ~ "Exceptionally High",
      y %in% 91:97 ~ "Above Average",
      y %in% 75:90 ~ "High-Average",
      y %in% 25:74 ~ "Average",
      y %in% 9:24 ~ "Low-Average",
      y %in% 2:8 ~ "Below Average",
      y < 2 ~ "Exceptionally Low",
      TRUE ~ as.character(y)
    )
  )

x <- c("Name", "Score", "Range")
y <- c("{point.name}", "{point.y}", "{point.range}")
tt <- tooltip_table(x, y)

# Create drilldown bar plot

frameWidget(
  highchart() %>%
    hc_title(text = patient,
             style = list(fontSize = "15px")) %>%
    hc_add_series(
      ncogL1statusz,
      type = "bar",
      name = "Neuropsychological Test Scores",
      hcaes(x = name, y = y, color = colors8)
    ) %>%
    hc_xAxis(
      type = "category",
      title = list(text = "Domain"),
      categories = .$name
    ) %>%
    hc_yAxis(
      title = list(text = "z-score"),
      labels = list(format = "{value}")
    ) %>%
    hc_tooltip(
      pointFormat = tt,
      useHTML = TRUE,
      valueDecimals = 0
    ) %>%
    hc_plotOptions(
      series = list(
        colorByPoint = TRUE,
        allowPointSelect = TRUE,
        dataLabels = TRUE
      )
    ) %>%
    hc_drilldown(
      allowPointDrilldown = TRUE,
      series = c(ncogL2drillz, ncogL3drillz, ncogL4drillz)
    )
)
```
